"""Culture-first profile models (the public, human-readable contract).

These models carry the *culture-first* output of the pipeline: a visible
Cultural Fingerprint (the four D1-D4 scores + plain readings), dynamic
model-named Cultural Themes whose observations are each grounded in evidence
``claim_ids``, grounded historical drivers, competing forces, relative-to-
neighbour insights, and reasoning-first council views.

Integrity rules enforced elsewhere (engine + deterministic assembly):
- every ``Observation`` / ``HistoricalDriver`` carries the ``claim_ids`` it was
  drawn from; ungrounded items are dropped by the grounding filter.
- ``sources_count`` (per item) and ``CulturalTheme.confidence`` (per theme) are
  computed deterministically, never invented by the model.
- snapshot readings, council views, and regional distinctiveness are assembled
  deterministically from existing structured data.
"""

from __future__ import annotations

from typing import ClassVar

from pydantic import BaseModel, Field, model_validator

from folk.models.enums import Dimension


def _as_str_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, (list, tuple, set)):
        return [str(v) for v in value if v is not None and str(v).strip()]
    return [str(value)]


class Observation(BaseModel):
    """One short, concrete, lived-experience statement grounded in evidence."""

    text: str = ""
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, str):
            return {"text": data}
        if isinstance(data, dict):
            if not data.get("text"):
                for k in ("text", "observation", "statement", "insight", "point"):
                    if data.get(k):
                        data["text"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class HistoricalDriver(Observation):
    """A grounded historical/structural reason a theme or country is the way it is.

    Same shape and grounding rules as :class:`Observation`."""


# Human-readable confidence bands. The UI shows these labels primarily; the
# raw 0-100 numbers stay available for sorting/tooltips.
CONFIDENCE_BANDS: tuple[tuple[int, str], ...] = (
    (85, "Very High"),
    (70, "High"),
    (50, "Moderate"),
    (30, "Low"),
    (0, "Contested"),
)


def confidence_label(score: int | float | None) -> str:
    """Map a 0-100 confidence score onto a band label.

    Contested (<30) / Low (<50) / Moderate (<70) / High (<85) / Very High (>=85).
    """
    if score is None:
        return "Contested"
    s = int(round(float(score)))
    for threshold, label in CONFIDENCE_BANDS:
        if s >= threshold:
            return label
    return "Contested"


class ThemeConfidence(BaseModel):
    """Transparent, three-part confidence for a theme (each 0-100) plus labels.

    Computed deterministically by the grounding filter, never invented:
    - ``evidence_strength``: how many distinct claims/sources/specialists back it.
    - ``expert_agreement``: how much the specialist seats agreed on the theme's
      dominant dimension.
    - ``framework_agreement``: cross-framework agreement on that dimension.

    The ``*_label`` fields are derived from the numbers (Contested / Low /
    Moderate / High / Very High) and are what the UI shows primarily.
    """

    evidence_strength: int = 0
    expert_agreement: int = 0
    framework_agreement: int = 0
    evidence_strength_label: str = ""
    expert_agreement_label: str = ""
    framework_agreement_label: str = ""
    # One-sentence, deterministically-composed "why this confidence" narrative
    # (computed by the engine, never invented by the model).
    confidence_explanation: str = ""

    @model_validator(mode="after")
    def _labels(self) -> "ThemeConfidence":
        self.evidence_strength_label = confidence_label(self.evidence_strength)
        self.expert_agreement_label = confidence_label(self.expert_agreement)
        self.framework_agreement_label = confidence_label(self.framework_agreement)
        return self


class CulturalTheme(BaseModel):
    """A dynamic, model-named cultural theme (e.g. 'Rules & Order', 'Nomadic
    Heritage') clustering grounded observations.

    ``title`` is generated by the model from the evidence (not a fixed bucket).
    ``confidence`` (a transparent three-part breakdown) and ``sources_count`` are
    computed deterministically by the grounding filter from how many distinct
    claims/sources/specialists back the theme, and drive the UI's
    Strong/Moderate/Emerging rating + sort.
    """

    title: str = ""
    confidence: ThemeConfidence = Field(default_factory=ThemeConfidence)
    sources_count: int = 0
    observations: list[Observation] = Field(default_factory=list)
    historical_roots: list[HistoricalDriver] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            if not data.get("title"):
                for k in ("title", "name", "theme", "label"):
                    if data.get(k):
                        data["title"] = str(data[k])
                        break
            if data.get("observations") is None:
                for k in ("observations", "bullets", "points", "items"):
                    if data.get(k) is not None:
                        data["observations"] = data[k]
                        break
            # The model may emit a bare numeric confidence; coerce to the
            # breakdown shape (the grounding filter recomputes it regardless).
            conf = data.get("confidence")
            if isinstance(conf, (int, float)):
                data["confidence"] = {"evidence_strength": int(conf)}
        return data


class LivedExperience(BaseModel):
    """The high-ROI 'what would surprise me if I lived there?' layer.

    Each list holds short, grounded :class:`Observation`s (claim-linked) about a
    single everyday-life domain. Ungrounded items are dropped by the filter."""

    daily_life: list[Observation] = Field(default_factory=list)
    workplace_norms: list[Observation] = Field(default_factory=list)
    communication_style: list[Observation] = Field(default_factory=list)
    friendship_social: list[Observation] = Field(default_factory=list)
    society: list[Observation] = Field(default_factory=list)
    social_mistakes_to_avoid: list[Observation] = Field(default_factory=list)
    status_signals: list[Observation] = Field(default_factory=list)

    FIELDS: ClassVar[tuple[str, ...]] = (
        "daily_life", "workplace_norms", "communication_style", "friendship_social",
        "society", "social_mistakes_to_avoid", "status_signals")

    def is_empty(self) -> bool:
        return not any(getattr(self, f) for f in self.FIELDS)

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            aliases = {
                "daily": "daily_life",
                "everyday_life": "daily_life",
                "workplace": "workplace_norms",
                "workplace_norm": "workplace_norms",
                "work": "workplace_norms",
                "communication": "communication_style",
                "friendship": "friendship_social",
                "friendships": "friendship_social",
                "social": "friendship_social",
                "relationships": "friendship_social",
                "public_life": "society",
                "societal": "society",
                "social_mistakes": "social_mistakes_to_avoid",
                "mistakes_to_avoid": "social_mistakes_to_avoid",
                "status": "status_signals",
            }
            for src, dst in aliases.items():
                if data.get(dst) is None and data.get(src) is not None:
                    data[dst] = data[src]
        return data


# Maps a research claim's ``life_domain`` tag onto a LivedExperience field.
# (The success_factor / failure_factor / communication_decoder /
# cultural_transition tags feed the dedicated top-level sections, not this map.)
LIFE_DOMAIN_TO_FIELD: dict[str, str] = {
    "daily_life": "daily_life",
    "workplace": "workplace_norms",
    "communication": "communication_style",
    "friendship_social": "friendship_social",
    "society": "society",
    "social_mistakes": "social_mistakes_to_avoid",
    "status_signals": "status_signals",
}


class CompetingForce(BaseModel):
    """A real cultural contradiction: the country pulls toward X but also toward
    Y, with a grounded ``explanation`` of why both are true at once.

    Grounding rules match :class:`Observation`: ``claim_ids`` is required and
    ungrounded forces are dropped by the filter; ``sources_count`` is computed.
    """

    pulls_toward: str = ""
    but_also: str = ""
    explanation: str = ""
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            if not data.get("pulls_toward"):
                for k in ("pulls_toward", "force", "tension", "one", "first", "paradox"):
                    if data.get(k):
                        data["pulls_toward"] = str(data[k])
                        break
            if not data.get("but_also"):
                for k in ("but_also", "counter", "but", "two", "second", "against"):
                    if data.get(k):
                        data["but_also"] = str(data[k])
                        break
            if not data.get("explanation"):
                for k in ("explanation", "why", "detail", "description"):
                    if data.get(k):
                        data["explanation"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class Archetype(BaseModel):
    """A memorable, country-specific cultural identity (e.g. 'The Precision
    Builder'). Grounded: kept only when its ``claim_ids`` resolve."""

    title: str = ""
    summary: str = ""
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, str):
            return {"title": data}
        if isinstance(data, dict):
            if not data.get("title"):
                for k in ("title", "name", "archetype", "label", "identity"):
                    if data.get(k):
                        data["title"] = str(data[k])
                        break
            if not data.get("summary"):
                for k in ("summary", "tagline", "description", "explanation", "text"):
                    if data.get(k):
                        data["summary"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class CommunicationSignal(BaseModel):
    """A 'communication decoder' entry: a literal phrase and what it really
    means here. Grounded; ungrounded entries are dropped."""

    phrase: str = ""
    meaning: str = ""
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            if not data.get("phrase"):
                for k in ("phrase", "they_say", "signal", "expression", "what_they_say"):
                    if data.get(k):
                        data["phrase"] = str(data[k])
                        break
            if not data.get("meaning"):
                for k in ("meaning", "means", "translation", "what_it_means", "decoded"):
                    if data.get(k):
                        data["meaning"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class TransitionAxis(BaseModel):
    """A 'culture in transition' axis: how a norm differs across a generational
    or urban/rural divide. Grounded; ungrounded entries are dropped."""

    axis: str = ""          # e.g. "Generational", "Urban vs rural"
    older: str = ""         # the more traditional pole
    younger: str = ""       # the more modern pole
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            if not data.get("axis"):
                for k in ("axis", "dimension", "contrast", "divide", "label", "title"):
                    if data.get(k):
                        data["axis"] = str(data[k])
                        break
            if not data.get("older"):
                for k in ("older", "traditional", "rural", "past", "from", "then"):
                    if data.get(k):
                        data["older"] = str(data[k])
                        break
            if not data.get("younger"):
                for k in ("younger", "modern", "urban", "future", "to", "now"):
                    if data.get(k):
                        data["younger"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class FriendshipFacet(BaseModel):
    """One facet of the friendship map (e.g. 'Making friends: Slow')."""

    label: str = ""         # short verdict, e.g. "Slow", "High", "Small"
    detail: str = ""        # optional one-line elaboration
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, str):
            return {"label": data}
        if isinstance(data, dict):
            if not data.get("label"):
                for k in ("label", "value", "verdict", "rating", "level", "text"):
                    if data.get(k):
                        data["label"] = str(data[k])
                        break
            if not data.get("detail"):
                for k in ("detail", "note", "explanation", "description"):
                    if data.get(k):
                        data["detail"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class FriendshipMap(BaseModel):
    """Structured 'how relationships work here' map. Each facet is grounded;
    ungrounded facets are dropped so empty facets stay hidden."""

    making_friends: FriendshipFacet = Field(default_factory=FriendshipFacet)
    friendship_depth: FriendshipFacet = Field(default_factory=FriendshipFacet)
    circle_size: FriendshipFacet = Field(default_factory=FriendshipFacet)
    trust_formation: FriendshipFacet = Field(default_factory=FriendshipFacet)
    work_personal_mixing: FriendshipFacet = Field(default_factory=FriendshipFacet)

    FIELDS: ClassVar[tuple[str, ...]] = (
        "making_friends", "friendship_depth", "circle_size",
        "trust_formation", "work_personal_mixing")

    def is_empty(self) -> bool:
        return not any(getattr(self, f).label for f in self.FIELDS)

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            aliases = {
                "ease_of_making_friends": "making_friends",
                "making": "making_friends",
                "depth": "friendship_depth",
                "depth_of_friendships": "friendship_depth",
                "circle": "circle_size",
                "typical_circle_size": "circle_size",
                "trust": "trust_formation",
                "trust_formation_speed": "trust_formation",
                "mixing": "work_personal_mixing",
                "work_personal": "work_personal_mixing",
                "mixing_work_and_personal_life": "work_personal_mixing",
            }
            for src, dst in aliases.items():
                if data.get(dst) is None and data.get(src) is not None:
                    data[dst] = data[src]
        return data


class SimilarCulture(BaseModel):
    """A culturally-close country with a grounded *explanation* of why (not just
    a name). The set is chosen deterministically; only the explanation is LLM."""

    iso3: str = ""
    country: str = ""
    similarity: int = 0
    explanation: str = ""
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            if data.get("iso3"):
                data["iso3"] = str(data["iso3"]).upper()
            if not data.get("explanation"):
                for k in ("explanation", "why", "reason", "detail", "text"):
                    if data.get(k):
                        data["explanation"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class UniquenessFacet(BaseModel):
    """A grounded 'why this country and not its nearest neighbours' facet.

    ``title`` is a short differentiator; ``explanation`` is one Pattern ->
    Explanation -> Consequence sentence. Grounded; ungrounded facets dropped."""

    title: str = ""
    explanation: str = ""
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            if not data.get("title"):
                for k in ("title", "name", "label", "facet", "heading"):
                    if data.get(k):
                        data["title"] = str(data[k])
                        break
            if not data.get("explanation"):
                for k in ("explanation", "why", "detail", "description", "text"):
                    if data.get(k):
                        data["explanation"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class ExperienceVariation(BaseModel):
    """How two real sub-populations experience the country differently (e.g.
    Urban professionals vs Rural communities). Grounded; ungrounded dropped.

    Distinct from :class:`TransitionAxis` (a temporal/generational *shift*):
    this captures co-existing group contrasts so the profile is not a single
    national stereotype."""

    group_a: str = ""
    group_b: str = ""
    difference: str = ""
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            if not data.get("group_a"):
                for k in ("group_a", "a", "first", "one", "group1", "left"):
                    if data.get(k):
                        data["group_a"] = str(data[k])
                        break
            if not data.get("group_b"):
                for k in ("group_b", "b", "second", "two", "group2", "right"):
                    if data.get(k):
                        data["group_b"] = str(data[k])
                        break
            if not data.get("difference"):
                for k in ("difference", "contrast", "explanation", "detail", "text", "how"):
                    if data.get(k):
                        data["difference"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class RelativeInsight(BaseModel):
    """Deterministic 'what makes this country unique' line vs a neighbour."""

    text: str = ""
    dimension: Dimension | None = None
    neighbour_iso3: str = ""
    delta: int = 0


class CouncilView(BaseModel):
    """A specialist's reasoning shown *before* the score they proposed."""

    specialist: str = ""
    reasoning: str = ""
    suggested_score: int = 50


class DimensionSnapshot(BaseModel):
    """One row of the visible Cultural Fingerprint: score + plain reading + a
    one-sentence cultural explanation.

    ``reading`` is the short deterministic label (e.g. "Strongly
    achievement-oriented"). ``explanation`` is a one-sentence grounded take on
    what the score means culturally; it falls back to ``reading`` when no
    grounded explanation survives."""

    dimension: Dimension
    score: int = 50
    reading: str = ""
    explanation: str = ""


class DimensionTake(BaseModel):
    """A grounded, one-sentence cultural explanation of a dimension's score.

    The cultural LLM emits these (keyed by dimension); the engine grounds them
    via ``claim_ids`` and merges the surviving text onto the matching
    :class:`DimensionSnapshot`."""

    dimension: Dimension | None = None
    explanation: str = ""
    claim_ids: list[str] = Field(default_factory=list)
    sources_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def _coalesce(cls, data):
        if isinstance(data, dict):
            dim = data.get("dimension") or data.get("dim") or data.get("code")
            if isinstance(dim, str):
                data["dimension"] = dim.strip().upper()
            if not data.get("explanation"):
                for k in ("explanation", "text", "take", "meaning", "reading"):
                    if data.get(k):
                        data["explanation"] = str(data[k])
                        break
            for k in ("claim_ids", "claims", "claim_id", "evidence", "sources"):
                if data.get(k) is not None:
                    data["claim_ids"] = _as_str_list(data[k])
                    break
        return data


class CulturalThemesDraft(BaseModel):
    """The ONLY part the cultural LLM produces - everything else is deterministic.

    The model clusters the provided evidence claims into self-named themes and
    short grounded bullets; the engine's deterministic grounding filter then
    drops ungrounded items and computes ``sources_count`` + ``confidence``."""

    executive_summary: str = ""
    cultural_archetype: Archetype = Field(default_factory=Archetype)
    good_for: list[str] = Field(default_factory=list)
    cultural_themes: list[CulturalTheme] = Field(default_factory=list)
    historical_drivers: list[HistoricalDriver] = Field(default_factory=list)
    competing_forces: list[CompetingForce] = Field(default_factory=list)
    lived_experience: LivedExperience = Field(default_factory=LivedExperience)
    life_feels_like: Observation = Field(default_factory=Observation)
    newcomer_first_impressions: list[Observation] = Field(default_factory=list)
    success_factors: list[Observation] = Field(default_factory=list)
    failure_factors: list[Observation] = Field(default_factory=list)
    friendship_map: FriendshipMap = Field(default_factory=FriendshipMap)
    communication_decoder: list[CommunicationSignal] = Field(default_factory=list)
    culture_in_transition: list[TransitionAxis] = Field(default_factory=list)
    experience_variations: list[ExperienceVariation] = Field(default_factory=list)
    similar_cultures: list[SimilarCulture] = Field(default_factory=list)
    country_uniqueness: list[UniquenessFacet] = Field(default_factory=list)
    dimension_takes: list[DimensionTake] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def _normalize(cls, data):
        if isinstance(data, dict):
            if data.get("cultural_themes") is None and data.get("themes") is not None:
                data["cultural_themes"] = data["themes"]
            # Accept the legacy `best_for` key as an alias for `good_for`.
            if data.get("good_for") is None and data.get("best_for") is not None:
                data["good_for"] = data["best_for"]
            if data.get("good_for") is not None:
                data["good_for"] = _as_str_list(data["good_for"])
            if data.get("cultural_archetype") is None and data.get("archetype") is not None:
                data["cultural_archetype"] = data["archetype"]
            for src, dst in (
                ("newcomers_notice_first", "newcomer_first_impressions"),
                ("first_impressions", "newcomer_first_impressions"),
                ("success_formula", "success_factors"),
                ("failure_formula", "failure_factors"),
                ("communication_signals", "communication_decoder"),
                ("transition", "culture_in_transition"),
                ("similar_countries", "similar_cultures"),
                ("life_feels_like_narrative", "life_feels_like"),
                ("what_life_feels_like", "life_feels_like"),
                ("group_variations", "experience_variations"),
                ("how_groups_differ", "experience_variations"),
                ("uniqueness", "country_uniqueness"),
                ("what_makes_unique", "country_uniqueness"),
                ("dimension_explanations", "dimension_takes"),
                ("dimension_takes", "dimension_takes"),
            ):
                if data.get(dst) is None and data.get(src) is not None:
                    data[dst] = data[src]
        return data


class CulturalProfile(BaseModel):
    """The culture-first, human-readable profile attached to a CountryProfile."""

    iso3: str = ""
    country: str = ""
    region: str | None = None

    # Visible Cultural Fingerprint (scores stay prominent).
    snapshot: list[DimensionSnapshot] = Field(default_factory=list)

    # Short, evidence-grounded LLM fields (produced in the one cultural call).
    executive_summary: str = ""
    cultural_archetype: Archetype = Field(default_factory=Archetype)
    good_for: list[str] = Field(default_factory=list)

    # Deterministic executive snapshot (4-6 one-sentence bullets, no LLM).
    culture_at_a_glance: list[str] = Field(default_factory=list)

    # Dynamic, grounded culture content.
    cultural_themes: list[CulturalTheme] = Field(default_factory=list)
    historical_drivers: list[HistoricalDriver] = Field(default_factory=list)
    competing_forces: list[CompetingForce] = Field(default_factory=list)

    # Lived-experience layer ('what would surprise me if I lived there?').
    lived_experience: LivedExperience = Field(default_factory=LivedExperience)
    life_feels_like: Observation = Field(default_factory=Observation)

    # Practical, grounded human-experience sections.
    newcomer_first_impressions: list[Observation] = Field(default_factory=list)
    success_factors: list[Observation] = Field(default_factory=list)
    failure_factors: list[Observation] = Field(default_factory=list)
    friendship_map: FriendshipMap = Field(default_factory=FriendshipMap)
    communication_decoder: list[CommunicationSignal] = Field(default_factory=list)
    culture_in_transition: list[TransitionAxis] = Field(default_factory=list)
    experience_variations: list[ExperienceVariation] = Field(default_factory=list)
    similar_cultures: list[SimilarCulture] = Field(default_factory=list)
    country_uniqueness: list[UniquenessFacet] = Field(default_factory=list)

    # Deterministic relative-to-neighbours context.
    regional_distinctiveness: list[RelativeInsight] = Field(default_factory=list)

    # Reasoning-first council views, keyed by dimension.
    council_views: dict[Dimension, list[CouncilView]] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _normalize(cls, data):
        """Tolerate LLM key-case variants (mirror narrative.py)."""
        if isinstance(data, dict):
            cv = data.get("council_views")
            if isinstance(cv, dict):
                data["council_views"] = {
                    (k.upper() if isinstance(k, str) else k): v for k, v in cv.items()
                }
            # Common alias: the model may emit "themes" instead of "cultural_themes".
            if data.get("cultural_themes") is None and data.get("themes") is not None:
                data["cultural_themes"] = data["themes"]
            if data.get("good_for") is None and data.get("best_for") is not None:
                data["good_for"] = data["best_for"]
            if data.get("good_for") is not None:
                data["good_for"] = _as_str_list(data["good_for"])
            if data.get("cultural_archetype") is None and data.get("archetype") is not None:
                data["cultural_archetype"] = data["archetype"]
            for src, dst in (
                ("life_feels_like_narrative", "life_feels_like"),
                ("what_life_feels_like", "life_feels_like"),
                ("group_variations", "experience_variations"),
                ("uniqueness", "country_uniqueness"),
            ):
                if data.get(dst) is None and data.get(src) is not None:
                    data[dst] = data[src]
        return data
